package com.example.composedemo

import com.example.composedemo.Person

class PersonRepo {

    fun getAllData():List<Person>{
        return listOf(
            Person(1,"Pradeep","HR"),
            Person(1,"Sohan","Shetty"),
            Person(1,"Manik","Deepak"),
            Person(1,"Harsh","Mishra"),
            Person(1,"Deepak","BV"),
            Person(1,"Pandugowda","Naganur"),
            Person(1,"Rajkumar","Aski"),
            Person(1,"Anurag","Patil"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Varun","Raj"),
            Person(1,"Chetan","Gowda")
        )
    }
}